sudo: required

services:
  - docker

branches:
  only:
    - master

env:
  - TAG=$(echo ${TRAVIS_BRANCH} | sed 's/[^0-9A-Za-z]/_/g')

before_script:
  - docker login -u=${DOCKER_USER} -p=${DOCKER_PASS}

script:
  - docker build -t agavelab/haproxy:${TAG} haproxy
  - docker build -t agavelab/letsencrypt:${TAG} letsencrypt
  - docker push agavelab/haproxy:${TAG}
  - docker push agavelab/letsencrypt:${TAG}

after_success:
  - docker history agavelab/haproxy:${TAG}
  - docker history agavelab/letsencrypt:${TAG}
